language: objective-c
osx_image: xcode11
xcode_project: FlawlessTransactionGeneration.xcodeproj
xcode_scheme: FlawlessTransactionGeneration
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 8

before_install:
- pod repo add artsy https://github.com/swiftoverflow/FlawlessValidation.git
after_success:
- slather
- bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode
